### ISSUE TITLE
the structure of Deblur arch is different from that in the paper

### ISSUE THREAD

**Issue by s1mple-boy** [xuboming8/DSTNet#3]
The arch named Deblur use 5 continuous TransformerBlock without self_attention, which correspond to CWGDN. This is completely different from that in the paper.
This arch path is basicsr/archs/deblur_arch.py. Did I find the wrong path of the arch named Deblur?

**Comment by xuboming8** [comment]
The details of CWGDN are consistent with the description in the paper. We have chosen to repeat this module five times as our final model.



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/30/2023 11:09 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [xuboming8/DSTNet] the structure of Deblur arch is different from that in the paper (Issue #3) |

The arch named Deblur use 5 continuous TransformerBlock without self_attention, which correspond to CWGDN. This is completely different from that in the paper.
This arch path is basicsr/archs/deblur_arch.py. Did I find the wrong path of the arch named Deblur?

**Comment by s1mple-boy** [comment]
Is the CWGDN named TransformerBlock in your code?

> The details of CWGDN are consistent with the description in the paper. We have chosen to repeat this module five times as our final model.
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/30/2023 11:09 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | [xuboming8/DSTNet] the structure of Deblur arch is different from that in the paper (Issue #3) | The arch named Deblur use 5 continuous TransformerBlock without self_attention, which correspond to CWGDN. This is completely different from that in the paper. This arch path is basicsr/archs/deblur_arch.py. Did I find the wrong path of the arch named Deblur? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by xuboming8** [comment]
Yes, as we followed the framework of restormer in this section, we did not modify the module names in this code. To better understand, I will modify the module names of CWGDN  in this code.



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/30/2023 18:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xuboming8/DSTNet] the structure of Deblur arch is different from that in the paper (Issue #3) |

Is the CWGDN named TransformerBlock in your code?

The details of CWGDN are consistent with the description in the paper. We have chosen to repeat this module five times as our final model.
…
---- Replied Message ---- | From | @.> | | Date | 09/30/2023 11:09 | | To | @.> | | Cc | @.> | | Subject | [xuboming8/DSTNet] the structure of Deblur arch is different from that in the paper (Issue #3) | The arch named Deblur use 5 continuous TransformerBlock without self_attention, which correspond to CWGDN. This is completely different from that in the paper. This arch path is basicsr/archs/deblur_arch.py. Did I find the wrong path of the arch named Deblur? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
