### ISSUE TITLE
Result problem

### ISSUE THREAD

**Issue by s1mple-boy** [xuboming8/DSTNet#4]
Sorry to bother you, I can't use your pretrained model GoPro.pth to get the same result as you in the Gopro dataset. Since this paper is accepted by cvpr23, this problem should be taken seriously.

**Comment by xuboming8** [comment]
Did you use the same test script I provided？（merge_full.py and calculate_psnr.py）



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/30/2023 16:42 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [xuboming8/DSTNet] Result problem (Issue #4) |

Sorry to bother you, I can't use your pretrained model GoPro.pth to get the same result as you in the Gopro dataset. Since this paper is accepted by cvpr23, this problem should be taken seriously.

**Comment by s1mple-boy** [comment]
Yes, I only change the dataset path and change the GoPro dataset structure as your demand.

> Did you use the same test script I provided？（merge_full.py and calculate_psnr.py）
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/30/2023 16:42 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | [xuboming8/DSTNet] Result problem (Issue #4) | Sorry to bother you, I can't use your pretrained model GoPro.pth to get the same result as you in the Gopro dataset. Since this paper is accepted by cvpr23, this problem should be taken seriously. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by xuboming8** [comment]
Can you provide more details about your testing process? The model GOPRO_large is correspond to test_deblur_GOPROL.Did you change the parameters in merge_full.py correctly?



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/30/2023 18:41 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [xuboming8/DSTNet] Result problem (Issue #4) |

Yes, I only change the dataset path and change the GoPro dataset structure as your demand.

Did you use the same test script I provided？（merge_full.py and calculate_psnr.py）
…
---- Replied Message ---- | From | @.> | | Date | 09/30/2023 16:42 | | To | @.> | | Cc | @.> | | Subject | [xuboming8/DSTNet] Result problem (Issue #4) | Sorry to bother you, I can't use your pretrained model GoPro.pth to get the same result as you in the Gopro dataset. Since this paper is accepted by cvpr23, this problem should be taken seriously. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

**Comment by s1mple-boy** [comment]
Sorry to bother you, when I prepare the dataset, I accidentally changed the order of the frames.I have resolved this problem. Thank you.

> Can you provide more details about your testing process? The model GOPRO_large is correspond to test_deblur_GOPROL.Did you change the parameters in merge_full.py correctly?
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 09/30/2023 18:41 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [xuboming8/DSTNet] Result problem (Issue #4) | Yes, I only change the dataset path and change the GoPro dataset structure as your demand. Did you use the same test script I provided？（merge_full.py and calculate_psnr.py） … ---- Replied Message ---- | From | @.> | | Date | 09/30/2023 16:42 | | To | @.> | | Cc | @.> | | Subject | [xuboming8/DSTNet] Result problem (Issue #4) | Sorry to bother you, I can't use your pretrained model GoPro.pth to get the same result as you in the Gopro dataset. Since this paper is accepted by cvpr23, this problem should be taken seriously. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>
